swagger: '2.0'
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: lofty-memento-315820.appspot.com
basePath: /
schemes:
  - https
security:
  - api_key: []
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: 'apiKey'
    name: 'key'
    in: 'query'
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      operationId: test
      produces:
        - application/json
      responses:
        200:
          description: OK
